<?php
session_start();
if(isset($_SESSION['loggedin'])){
  if(!$_SESSION['loggedin']){
    header('Location: ./');
  }
}
else{
  header('Location: ./');
}
$data = "";
require './db_connection.php';
if(isset($_POST['data'])){
  if($_POST['data'] == 'latest'){
    $retrieve_logs = $connection->prepare("SELECT Directory, Vehicle, Passengers, Route, LogDate, LogTime FROM logs ORDER BY LogId ASC");
  }elseif($_POST['data'] == 'oldest'){
    $retrieve_logs = $connection->prepare("SELECT Directory, Vehicle, Passengers, Route, LogDate, LogTime FROM logs ORDER BY LogId DESC");
  }
}elseif(isset($_POST['startdate']) && isset($_POST['enddate'])){
  $start_date = $_POST['startdate'];
  $end_date = $_POST['enddate'];
  $retrieve_logs = $connection->prepare("SELECT Directory, Vehicle, Passengers, Route, LogDate, LogTime FROM logs WHERE LogDate BETWEEN '$start_date' AND '$end_date'");
}else{
  $retrieve_logs = $connection->prepare("SELECT Directory, Vehicle, Passengers, Route, LogDate, LogTime FROM logs");
}
try{
  $retrieve_logs->execute();
  $logs = $retrieve_logs->fetchAll();
  if(sizeof($logs) > 0){
    foreach($logs as $log){
      echo "<div id='vehicle-logs-container'>";
      echo "<div>";
      echo "<div class='card-header' id='v-l'>";
      echo "<h5 class='mb-0'>";
      echo "<button style='width: 100%;' class='btn btn-link collapsed' data-toggle='collapse' data-target='#logsContent' aria-expanded='true' aria-controls='collapseOne'>";
      echo "<div style='display: flex; align-items: center; justify-content: space-between; width: 100%;'>";
      echo "<div style='display: flex;'>";
      echo "<i class='fas fa-file' style='font-size: 35px;'></i>";
      echo "<div style='width: 100px; padding: 5px;' id='vh-name'>" . $log['Vehicle'] . "</div>";
      echo "</div>";
      echo "<div id='dt-created'>" . $log['LogDate'] . "_" . $log['LogTime'] . "</div>";
      echo "</div>";
      echo "</button>";
      echo "</h5>";
      echo "</div>";
      echo "<div id='logsContent' style='text-align: center;' class='collapse' aria-labelledby='v-l' data-parent='#vehicle-logs-container'>";
      echo "<div display='flex' style='margin: 10px 0 10px 0'><button class='btn btn-primary' onclick='saveLogPDF()'>SAVE AS PDF</button></div>";
      echo "<div id='areatoprint' class='card-body'>";
      echo "<div style='text-align: center'>";
      echo "<img style='width: 50px; height: 50px;' src='./images/logoQrmoc.png'>";
      echo "<div style='font-size: 14px; font-family: Times New Roman; padding: 5px 0 3px 0; font-weight: bold'>Authentic Log of " . $log['Vehicle'] . "</div>";
      echo "<div style='font-size: 14px; font-family: Times New Roman; padding: 2px 0 20px 0; font-weight: bold'>Generated by Q R M O C - Queuing Passenger Assistance System</div>";
      echo "</div>";
      $log_content = json_decode(file_get_contents($log['Directory']));
      echo "<table style='width: 100%'>";
      echo "<tr><th>No</th><th>Passenger</th><th>Companion</th></tr>";
      $count = 0;
      foreach($log_content as $info){
        if(isset($info->queuetime) && isset($info->leavetime)){
          echo "<table style='width: 100%'>";
          echo "<tr><th>Time Queued</th><th>Time Departed</th></tr>";
          echo "<tr><td>" . $info->queuetime . "</td><td>" . $info->leavetime . "</td></tr>";
          echo "</table>";
        }else{
          $count += 1;
          echo "<tr>";
          echo "<td>" . $count . "</td>";
          echo "<td>";
          if($info->Name == ""){
            echo "N/A";
          }else{
            echo $info->Name;
          }
          echo "</td>";
          echo "<td>";
          if($info->Companion){
            echo "<i class='fas fa-check'></i>";
          }else{
            echo "<i class='fas fa-times'></i>";
          }
          echo "</td>";
          echo "</tr>";
        }
      }
      echo "</table>";
      echo "<div style='padding: 5px 0 0 0; display: flex; justify-content: space-between;'><div style='font-family: Times New Roman; font-size: 14px'>Number of Passengers: " . $log['Passengers'] . "</div><div style='font-family: Times New Roman; font-size: 14px'>Made possible by J<sup>3</sup></div></div>";
      echo "</div>";
      echo "</div>";
      echo "</div>";
      echo "</div>";
    }
  }else{
    echo "<tr><td colspan='5'>No logs found</td></tr>";
  }
}catch(Exception $e){
  echo "error";
}
echo "</table>";
?>
